### ISSUE TITLE
Filter field repositions itself (not related to Customize Toolbar)

### ISSUE THREAD

**Issue by kiwichick888** [peter-frentrup/NppMenuSearch#38] opened 2022-11-15 03:35 UTC
Why does the filter field keep resetting itself? By default, after install, it's cut off at the end of the toolbar. I reposition it and it stays there until I resize the Npp window eg: from maximised to a smaller window. If re-maximise the window the filter field goes back to where I positioned it. But, if I close Npp while the window is resized, re-open Npp and maximise the window, the filter field has reset itself to the default position cut off at the end of the toolbar. 

In a previous issue raised about this, it was said that having Customize Toolbar installed is what's causing this and yes I do have it installed. However, I tried a fresh install of Npp with only NppMenuSearch installed. By default, after install, it was not cut off at the end of the toolbar but, if I do the same window resize, reopen and maximise, the same behaviour happens.

I hope that all made sense.

There also seems to be conflict with some other plugin (not Customize Toolbar) that causes NppMenuSearch to not uninstall. Again, I checked with a clean install of Npp and only NppMenuSearch and Customize Toolbar installed and NppMenuSearch uninstalled.

![2022-11-02_112224](https://user-images.githubusercontent.com/6602525/201820237-d8c33e87-a3c8-4ab3-98c0-a293b5846617.png)

**Comment by peter-frentrup** [comment] 2022-11-15 20:09
Hello,
thank you for your report. I believe this is a duplicate of (the second issue mentioned in) issue #37.

The resizing logic is how the [Windows Rebar control](https://learn.microsoft.com/en-us/windows/win32/controls/rebar-controls) works. There is not a lot I can do.

Peter

**Closed** 2023-08-02 17:53 UTC
Labels: duplicate
