### ISSUE TITLE
Access Violation as of Notepad++ commit 84c1505

### ISSUE THREAD

**Issue by vinsworldcom** [peter-frentrup/NppMenuSearch#28] opened 2021-09-03 18:06 UTC
@peter-frentrup 

As of Notepad++ commit [84c1505](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/84c1505fab9a0ec4aaadc170daad43342ee95c58), the plugin crashes with Access Violation error (it doesn't even load).

Using Windows 10 64-bit with Notepad++ (commit referenced above), 64-bit.

**Comment by peter-frentrup** [comment] 2021-09-03 23:43
Hello,
thank you for your report. The mentioned commit [84c1505](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/84c1505fab9a0ec4aaadc170daad43342ee95c58) has a malformed *english.xml*: `&&` should be written as `&amp;&amp;`.
Would fixing that help? (I cannot reproduce the crash here).

Best regards,
Peter

**Comment by vinsworldcom** [comment] 2021-09-04 00:50
@peter-frentrup - thank you so much for responding and continuing to support this excellent plugin.  I never search Notepad++ menus for operations I want, I just call this plugin and type some related word and find the function I want.  I use it during every Notepad++ editing session.

I tied fixing the english.xml manually - didn't seem to work.  So I got a fresh copy of [Notepad++ 8.1.4](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.1.4/npp.8.1.4.portable.x64.zip) and unzipped to a local directory.  I upgraded the `notepad++.exe` only to the [c1cce29](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c1cce29c8460dd227963fa8615344d15af4ccc09) commit [here](https://ci.appveyor.com/api/buildjobs/3ahb2i3vgm4wik7a/artifacts/Notepad%2B%2B.x64.Release.exe) which fixes that error (according to the commit message.  I added the NppMenuSearch plugin and still get the access violation.

Cheers.

**Comment by peter-frentrup** [comment] 2021-09-04 09:53
Dear @vinsworldcom,
I was able to reproduce the issue. The root cause is that Notepad++ commit [84c1505 ](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/84c1505fab9a0ec4aaadc170daad43342ee95c58) added two static controls with the same control identifier `IDC_STATIC` to the preferences dialog `PowerEditor/src/WinControls/Preference/preference.rc`. I am currently implementing a workaround.

Cheers, Peter

**Comment by vinsworldcom** [comment] 2021-09-04 14:11
> Notepad++ commit [84c1505 ](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/84c1505fab9a0ec4aaadc170daad43342ee95c58) added two static controls with the same control identifier `IDC_STATIC` to the preferences dialog `PowerEditor/src/WinControls/Preference/preference.rc`

Is that lines 395, 396?

**Comment by peter-frentrup** [comment] 2021-09-04 18:37
Yes, those two lines.

The issue should be fixed with version 0.9.5

**Closed by peter-frentrup** 2021-09-04 18:37 UTC

**Comment by vinsworldcom** [comment] 2021-09-04 19:08
> The issue should be fixed with version 0.9.5

INDEED - it is!  Just tested.  THANK YOU for the quick response and continued support of this excellent plugin.

Cheers.
