### ISSUE TITLE
Plugin causes notepad++.exe process to remain open after quitting app

### ISSUE THREAD

**Issue by favorini** [peter-frentrup/NppMenuSearch#13] opened 2018-01-12 03:29 UTC
Tried version 0.9.0 and 0.9.2 with Notepad++ 7.5.4 32-biit on Windows 7 x64. If I remove NppMenuSearch, process exits as expected. See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4062 for more info.

**Comment by chcg** [comment] 2018-01-30 21:11
And see also https://notepad-plus-plus.org/community/topic/15163/process-explorer-shows-npp-instances-remain-after-closing

**Comment by Big--Mike** [comment] 2018-04-23 13:14
I realized it's a conflict with NPPMenuSearch and DSpellcheck. If I remove one of the both, all is working fine

**Comment by jckleinbourg** [comment] 2018-09-21 16:07
As I said in the other thread, plugin 'Explorer v1.8.2' causes exactly the same issue.

I found that it was this one which was causing problem in my case by tracking the dll remaining with Process Explorer as explained here: https://superuser.com/questions/675789/how-to-kill-a-task-that-is-lacking-an-instance

**Comment by dinkumoil** [comment] 2018-11-20 21:48
I already reported a bug concerning this issue on [SourceForge](https://sourceforge.net/p/nppmenusearch/bugs/12/). I haven't installed _DSpellCheck_ and are facing the hung Npp process either.

There is definitely an interconnection with the presence and/or absence of other plugins. At my site the problem disappears when _NppFTP_ plugin gets installed.

An additional issue with the _MenuSearch_ plugin is that it causes loss of content of the file _favorites.dat_ belonging to the _Explorer_ plugin, [see here](https://sourceforge.net/p/nppmenusearch/bugs/13/).

**Comment by brgrvrm** [comment] 2019-06-07 07:25
I'm also facing the problem that notepad++.exe process remains active when closing the notepad++ app. This only happens with other plugins installed.

In my case it is when NppMenuSearch and [jN npp plugin](https://github.com/sieukrem/jn-npp-plugin) are installed. It seems to be a problem with NppMenuSearch plugin that is triggered by other plugins. 

Sadly it looks like NppMenuSearch is not in active development by @peter-frentrup. But @budul100 did some commits in the past. Hopefully someone can dig into this issue. NppMenuSearch is a daily driver and we will badly miss the power it has.

Notepad++ 7.7.0 (32 bit)
NppMenuSearch 0.9.2 (32 bit)
JN npp plugin 2.2.185.5 (32 bit)

**Comment by shriprem** [comment] 2019-10-12 23:34
I noticed this issue with the 64-bit version of the plugin. The 32-bit version has worked fine.

I then downloaded the source code, and started playing with it. I think I may have a solution. The issue is with the `Main.cs >> PluginCleanup()` method. I had to comment out the line with `ReleaseHandle()` call. Here is the changed version of the method:
```
internal static void PluginCleanUp()
{
    Settings.Save(xmlFilePath);
    //NppListener.ReleaseHandle();
}

```
Notes: 
1. I tried substituting the `ReleaseHandle` call with a `DestroyHandle` call. Notepad++ seemed to close fine. But on the next launch, it launched with a reduced font size. I believe the handle release/destroy is best left to be managed internally by the NativeWindow ancestor class of the NppListener class. I am not an experienced coder in C#. So others will have a better insight into this.
2. After the code change, I first had to once do a build in the Debug mode (x32 or x64 didn't matter). Only therafter, the release version for both the 32-bit and 64-bit DLLs started loading in corresponding versions of Notepad++ without a Unicode-related error. I am using Visual Studio 2019. Again, I have to admit that C# is not something in which I have coded anything significant.
If the author of this plugin (many thanks to him for this useful plugin!) or someone more knowledgeable in C# than me can review the change, do a fork, and provide the patched DLLs, I am fine with it. Otherwise, if anyone is interested that I take the initiative and provide the patched DLLs, please let me know. Thanks.

**Comment by peter-frentrup** [comment] 2019-10-22 21:15
Dear @shriprem,
thank you for your effort. After some testing I think your workaround of just not calling ReleaseHandle() is the best solution. I will apply the fix.

**Closed** 2019-10-22 21:15 UTC

**Comment by pidgeon777** [comment] 2019-11-26 20:33
I also had this problem when enabling FingerText and/or NppExec, with NppMenuSearch active, too. Glad this has been fixed.
